services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - eridanus-net

  eridanus:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: eridanus
    restart: always
    ports:
      - "5007:5007"
    depends_on:
      - redis
    networks:
      - eridanus-net

networks:
  eridanus-net:
    driver: bridge
