version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - qqbot-net

  napcat:
    image: docker.1ms.run/mlikiowa/napcat-docker:latest
    container_name: napcat
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6099:6099"
    restart: always
    networks:
      - qqbot-net

  eridanus:
    image: crpi-3gef5glpjhp2r3tx.cn-hangzhou.personal.cr.aliyuncs.com/sorahub/eridanus-docker:latest
    container_name: eridanus
    restart: always
    ports:
      - "5007:5007"
    depends_on:
      - redis
      - napcat
    networks:
      - qqbot-net

networks:
  qqbot-net:
    driver: bridge
