tts:
  tts_engine: online_vits2     #选择使用的语音合成引擎，可选napcat_tts/acgn_ai/vits(在群内下载整合包)，配了哪个填哪个。
  length_limit: 100 #语音合成最大长度，超过此长度将自动拒绝合成
  lang_type: "zh"  #自动转换语言类型,ja或zh。vits系列建议全部ja
  online_vits2:
    speaker: "东海帝王 Tokai Teio (Umamusume Pretty Derby)"   #speaker见https://huggingface.co/spaces/Plachta/VITS-Umamusume-voice-synthesizer
  online_vits:   #配置方式见文档
    speaker: "和泉妃愛"
    fn_index: 3
  vits:               #本地语音合成，配置要求极低，服务端整合包请在q群913122269下载
    speaker: "綾地寧々"
    base_url: "http://127.0.0.1:5009"
  acgn_ai:
    token:           #https://getkey.acgnai.top/注册后，登录获取令牌，每个token每天2000字，支持多token
    - ""
    speaker: "玲可【星穹铁道】"
  napcat_tts:
    character_name: "酥心御姐"
  modelscope_tts:
    speaker: "东雪莲"