llm:
  model: default #选择使用的模型大类。default为自带免费模型，可选openai、gemini。
  system: "你现在是一只猫娘，你的名字是{bot_name}，我的名字是{用户}，是你的主人。注意，你需要在回复时避免使用markdown语法。" #修改后要用【/全切人设 0】(不要带括号，不要带艾特，在群里发)为所有人刷新。
  chara_file_name: 猫娘.txt   #system为""时生效 默认启动的人设文件名，在data/system/chara文件夹内(目前支持txt,json,酒馆角色卡(图片))
  func_calling: True  #开启函数调用功能
  表情包发送: true      #记录master发送的表情包并在回复时根据上下文发送。
  单次发送表情包数量: 1  #单次发送最大表情包数量
  联网搜索: false      #官方版本联网搜索，与函数调用不可同时开启
  联网搜索显示原始数据: True   #此处联网搜索基于函数调用实现(非官方)，与上面的联网搜索不同，所以可以同时开启函数调用和实现联网搜索。
  读取群聊上下文: true  #开启上下文读取功能，可读取群聊历史消息，并根据上下文进行回复。
  可获取的群聊上下文长度: 10
  prefix: #可以用于触发bot的指令前缀
    - "测试机"
  aiReplyCore: True   #ai回复核心，将优化其他功能回复表现
  enable_proxy: False
  max_history_length: 40 #最大上下文长度
  Quote: False     #回复时引用
  focus_time: 10    #单次触发对话后持续有效时间
  语音回复几率: 30
  语音回复附带文本: True
  recursion_limit: 10                  #对话模型最大递归深度，出错时自动递归。
  auto_clear_when_recursion_failed: True #对话模型递归失败时自动清除历史记录。
  openai:          #兼容所有openai标准接口。https://platform.openai.com/docs/overview
    enable_official_sdk: True   #是否使用官方sdk，如果不使用，则为直接发送post请求。
    api_keys:   #继续像这样添加apikey
    - YOUR_API_KEY_1
    model: deepseek-reasoner
    quest_url: https://api.deepseek.com   #如使用官方sdk，则只填base_url，否则填完整url。
    temperature: 1.3
    max_tokens: 2048
    CoT: True               #显示思维链
    使用旧版prompt结构: false  #部分模型需要使用旧版prompt结构
  gemini:         #https://ai.google.dev/
    api_keys:  #继续像这样添加apikey
      - YOUR_API_KEY_1
    model: gemini-2.0-flash-001
    base_url: https://generativelanguage.googleapis.com #后面的/v1/beta什么的会自动填充
    temperature: 0.7
    maxOutputTokens: 2048
  腾讯元器:     #极其不建议用，腾子搞得玩意稀烂，而且不支持函数调用。
    智能体ID: ""
    token: ""
core:
  ai_reply_group: 0    #群内ai对话所需权限等级
  ai_reply_private: 0  #私聊ai对话所需权限等级
  ai_change_character: 0  #ai更换角色所需权限等级
  ai_token_limt: 0 #不限制ai对话token所需权限等级
  ai_token_limt_token: 10000 #一般用户限制ai对话token数量