steamsnooping:
  is_snooping: True   #是否开启Steam视奸功能
  steam_api_key:      #需要您自行申请写入一个或多个Steam Api Key，申请地址：https://partner.steamgames.com/doc/webapi_overview/auth
    - A3780E7FA6FEB3C9E0A17DE6E2A51CFF
