user_data:
  auto_register: true  #自动为发送消息的用户注册。确保所有人都在数据库中，不建议关。
  change_info_operate_level: 0     #相关指令所需操作权限等级。默认0级最低，数字越大等级越高
  permit_user_operate_level: 998   #允许使用授权#{目标QQ}#{level} 指令的操作权限等级
api_implement:
  send_like: 0    #“赞我”功能所需权限等级
core:
  ai_reply_group: 0    #群内ai对话所需权限等级
  ai_reply_private: 0  #私聊ai对话所需权限等级
  ai_change_character: 0  #ai更换角色所需权限等级
  ai_token_limt: 0 #不限制ai对话token所需权限等级
  ai_token_limt_token: 10000 #一般用户限制ai对话token数量
resource_search: #资源搜索功能
  z_library:
    search_operate_level: 0    #书籍搜索所需等级
    download_operate_level: 998  #书籍下载所需等级
  asmr:
    asmr_level: 0
  jmcomic:
    jm_comic_search_level: 0  #jm搜索功能所需权限等级
    jm_comic_download_level: 0          #jm下载功能所需权限等级
  iwara:
    iwara_search_level: 0  #iwara搜索功能所需权限等级
    iwara_download_level: 998  #iwara下载功能所需权限等级
basic_plugin:
  setu_operate_level: 0    #色图功能所需等级
  search_image_resource_operate_level: 0  #图片搜索功能所需等级
  recall_level: 3 #撤回？
  内置ai绘画1开关: true  #聚合接口
  内置ai绘画2开关: true  #NoobXL-V-pred-v1.0，来自modelscope。
  内置ai绘画1所需权限等级: 0  #默认聚合绘图功能所需等级
  内置ai绘画2所需权限等级: 0  #NoobXL-V-pred-v1.0
流媒体:
  youtube:
    download_audio_level: 0  #下载音频所需权限等级
    download_video_level: 30  #下载视频所需权限等级
  asmr:
    download_audio_level: 0  #下载音频所需权限等级
