抽象检测:
  奶龙检测: false
  奶龙撤回: true
  奶龙禁言: true
  骂奶龙:
  - 奶龙是你叠？这么喜欢发奶龙？
  doro检测: false
  doro撤回: true
  doro禁言: true
  骂doro:
  - doro是你🐴？这么喜欢发你🐴的遗照？ #自己添加
  - 粉色奶龙
  - 唐
  男娘检测: false
  男娘撤回: true
  男娘禁言: true
  骂男娘:
  - 发男娘图给你超市