llm:
  model: default #选择使用的模型大类。default为自带免费模型，可选openai、gemini。
  system: "你现在是一只猫娘，你的名字是{bot_name}，我的名字是{用户}，是你的主人。注意，你需要在回复时避免使用markdown语法。" #修改后要用【/全切人设 0】(不要带括号，不要带艾特，在群里发)为所有人刷新。
  chara_file_name: 猫娘.txt   #system为""时生效 默认启动的人设文件名，在data/system/chara文件夹内(目前支持txt,json,酒馆角色卡(图片))
  func_calling: True  #开启函数调用功能
  表情包发送: true      #记录master发送的表情包并在回复时根据上下文发送。
  单次发送表情包数量: 1  #单次发送最大表情包数量
  联网搜索: false      #官方版本联网搜索，与函数调用不可同时开启
  联网搜索显示原始数据: True   #此处联网搜索基于函数调用实现(非官方)，与上面的联网搜索不同，所以可以同时开启函数调用和实现联网搜索。
  读取群聊上下文: true  #开启上下文读取功能，可读取群聊历史消息，并根据上下文进行回复。
  可获取的群聊上下文长度: 10
  prefix: #可以用于触发bot的指令前缀
    - "测试机"
  aiReplyCore: True   #ai回复核心，将优化其他功能回复表现
  enable_proxy: False
  max_history_length: 40 #最大上下文长度
  Quote: False     #回复时引用
  focus_time: 10    #单次触发对话后持续有效时间
  语音回复几率: 30
  语音回复附带文本: True
  recursion_limit: 10                  #对话模型最大递归深度，出错时自动递归。
  auto_clear_when_recursion_failed: True #对话模型递归失败时自动清除历史记录。
  openai:          #兼容所有openai标准接口。https://platform.openai.com/docs/overview
    enable_official_sdk: True   #是否使用官方sdk，如果不使用，则为直接发送post请求。
    api_keys:   #继续像这样添加apikey
    - YOUR_API_KEY_1
    model: deepseek-reasoner
    quest_url: https://api.deepseek.com   #如使用官方sdk，则只填base_url，否则填完整url。
    temperature: 1.3
    max_tokens: 2048
    CoT: True               #显示思维链
    使用旧版prompt结构: false  #部分模型需要使用旧版prompt结构
  gemini:         #https://ai.google.dev/
    api_keys:  #继续像这样添加apikey
      - YOUR_API_KEY_1
    model: gemini-2.0-flash-001
    base_url: https://generativelanguage.googleapis.com #后面的/v1/beta什么的会自动填充
    temperature: 0.7
    maxOutputTokens: 2048
  腾讯元器:     #极其不建议用，腾子搞得玩意稀烂，而且不支持函数调用。
    智能体ID: ""
    token: ""
tts:
  tts_engine: online_vits2     #选择使用的语音合成引擎，可选napcat_tts/acgn_ai/vits(在群内下载整合包)，配了哪个填哪个。
  length_limit: 100 #语音合成最大长度，超过此长度将自动拒绝合成
  lang_type: "zh"  #自动转换语言类型,ja或zh。vits系列建议全部ja
  online_vits2:
    speaker: "东海帝王 Tokai Teio (Umamusume Pretty Derby)"   #speaker见https://huggingface.co/spaces/Plachta/VITS-Umamusume-voice-synthesizer
  online_vits:   #配置方式见文档
    speaker: "和泉妃愛"
    fn_index: 3
  vits:               #本地语音合成，配置要求极低，服务端整合包请在q群913122269下载
    speaker: "綾地寧々"
    base_url: "http://127.0.0.1:5009"
  acgn_ai:
    token:           #https://getkey.acgnai.top/注册后，登录获取令牌，每个token每天2000字，支持多token
    - ""
    speaker: "玲可【星穹铁道】"
  napcat_tts:
    character_name: "酥心御姐"
  modelscope_tts:
    speaker: "东雪莲"
proxy:
  http_proxy: ""
  socks_proxy: ""
心知天气:
  api_key: ""     #https://www.seniverse.com/ 申请后，填私钥
image_search:
  sauceno_api_key: ""          #sauceno搜图api，你可以从https://saucenao.com/user.php注册并获取
z_library:       #填你的zlib账号，此功能需要开启代理。
  search_num: 4        #搜索返回结果数量，默认4本书
  email: ""
  password: ""  #快填，Eridanus会偷走你的账号密码
youtube_asmr:
  send_type: file   #record或者file，record是语音，file是文件
  channels:          #频道来源。此功能需要配置proxy，并通过tools完成登录。
    - '@emococh'
    - '@-gabisroom-4153'
today_wife:
  api:
  - 'http://127.0.0.1:5000/today_wife'  #今日老婆的获取api，可以替换成自己的图床，可以添加多个链接
  - 'https://api.iw233.cn/api.php?sort=top'
  header: 'https://weibo.com/'          #知道的自己改，不知道的不要动
  wifePrefix: '/'                       #透群友的指令前缀
  复读开关: True
  签🦌撤回: True
  透群友撤回: True
  透热门群友: True #只会透到最近发言较多的群友


nasa_api:
  api_key: ""   #nasa的每日天文api 从https://api.nasa.gov/index.html#main-content申请
