bot_config:
  user_handle_logic: blacklist #模式。可填 blacklist, whitelist。blacklist下，屏蔽指定用户，whitelist下，只处理指定用户。
  user_handle_logic_operate_level: 1000 #拉黑、解黑用户所需操作权限
  group_handle_logic: blacklist #模式。可填 blacklist, whitelist。blacklist下，屏蔽指定群，whitelist下，只处理指定群。
  group_handle_logic_operate_level: 1000 #拉黑、解黑群所需操作权限
  邀请bot加群所需权限: 0
  申请bot好友所需权限: 0
  record_mface: true #是否收集主人的表情包
api_implements: #花里胡哨
   nudge:               #戳一戳设置。
     counter_probability: 100 #反击概率
     replylist:       #如果开启aiReplyCore，将不使用此处配置回复
       - "戳我干嘛呀！"
acg_information:
  bangumi_query_prefix: "/" #番剧查询类命令前缀
basic_plugin:
  setu:
    r18mode: true
    download: true #关掉的话就是直接发送url，灰度图不生效。
    gray_layer: true #是否开启灰度图功能
  tarot:
    lock: false #是否开启卡片锁定功能，现在没写锁定，开了也没用
    mode: "blueArchive" #牌面。可填 blueArchive,bilibili,AbstractImages
    彩蛋牌:
      enable: true #是否开启彩蛋牌
      probability: 5 #彩蛋牌出现概率
      card_index:
        - data/pictures/tarot/hidden_tarot/dio.jpg: ""
        - data/pictures/tarot/hidden_tarot/GIOGIO.jpg: ""
        - data/pictures/tarot/hidden_tarot/gyro.jpg: ""
        - data/pictures/tarot/hidden_tarot/hp.jpg: ""
        - data/pictures/tarot/hidden_tarot/johnny.jpg: ""
        - data/pictures/tarot/hidden_tarot/joseph.jpg: ""
        - data/pictures/tarot/hidden_tarot/vlt.jpg: ""
  搜图:
    聚合搜图: true          #搜单图
    soutu_bot: true       #搜本子
  绘图框架:
    gal_recommend: True   #galgame推荐是否接入绘图框架，若false则聊天记录发送
    majsoul_search: True  #雀魂搜索功能是否接入绘图框架，若false则文字发送

JMComic:                  #禁漫相关功能设置
  anti_nsfw: black_and_white   #防吞策略，可选gif、black_and_white、no_censor
  gif_compress: false     #gif模式下是否压缩
  previewPages: 6         #验车预览页数
  autoClearPDF: True      #下载后自动清除pdf
  savePath: "data/pictures/benzi"  #下载为pdf的默认保存路径
asmr:
  with_url: false  #是否附带同作品集其他作品的url
  with_file: false #是否合并并发送音频文件
  max_merge_file_num: 10 #最大合并文件数
  gray_layer: true #是否开启灰度图功能

bili_dynamic:     #下面的设置暂不可用，请暂时不要修改
  enable: true    #是否开启动态推送功能
  dynamic_interval: 300 #动态推送间隔时间，单位为秒
  screen_shot_mode: "mobile" #mobile为移动端截图，pc为PC端截图
  draw_type: 2    #1代表用playwright（需要安装其余组件）；2代表本地Pillow绘图（有可能出错）
  is_QQ_chek: True #是否检测qq小程序里的视频链接

网易云卡片:    #绘制网易云歌曲分享卡片
  enable: true
  解析自带音频下载url: false #涉及付费音乐版权问题，只能以文件形式发送了,不允许进行传播、销售等商业活动!!

抽象检测:
  奶龙检测: false
  奶龙撤回: true
  奶龙禁言: true
  骂奶龙:
  - 奶龙是你叠？这么喜欢发奶龙？
  doro检测: false
  doro撤回: true
  doro禁言: true
  骂doro:
  - doro是你🐴？这么喜欢发你🐴的遗照？ #自己添加
  - 粉色奶龙
  - 唐
  男娘检测: false
  男娘撤回: true
  男娘禁言: true
  骂男娘:
  - 发男娘图给你超市
scheduledTasks:    #其他定时任务模块的内容会陆续转到这里
  早安问候:         #晨间推送
    enable: true  #向信任用户推送天气信息
    time: 8/3      #推送时间
    trustThreshold: 9 #权限等级要求，低于此值的用户将不会被推送
    onlyTrustUser: True  #仅向信任用户推送
  晚安问候: #晚安提示
    enable: true
    text: 晚安！    #开启aiReplyCore后，此项将被ai替代
    time: 22/31
    trustThreshold: 9 #低于权限等级的用户将不会被推送
    onlyTrustUser: True  #仅向信任用户推送
  bangumi:         #bangumi推送
    enable: True
    text: "晚上好，这里是今天的bangumi推送"
    time: 19/16
  每日天文:       #nasa天文推送
    enable: True
    text: "今日nasa天文推送"
    time: 18/59
  单向历:      #单向历
    enable: true
    text: 今日单向历
    time: 19/2
  摸鱼人日历:            #摸鱼人日历
    enable: true
    text: 真没用啊，又在摸鱼了吧，杂鱼❤
    time: 17/30
  新闻:            #新闻
    enable: true
    text: 早上好杂鱼❤，这里是今天的新闻
    time: 8/2
  免费游戏喜加一:       #免费游戏提示
    enable: true
    text: 杂鱼❤来白嫖游戏了
    time: 12/2
  nightASMR:
    enable: true
    text: 听完就赶紧睡觉吧~祝你好梦！(≧▽≦*)
    time: 22/35
  bing每日图像:
    enable: true
    time: 10/2
