z_library:       #填你的zlib账号，此功能需要开启代理。
  search_num: 4        #搜索返回结果数量，默认4本书
  email: ""
  password: ""  #快填，Eridanus会偷走你的账号密码
  search_operate_level: 0    #书籍搜索所需等级
  download_operate_level: 998  #书籍下载所需等级
asmr:
  with_url: false  #是否附带同作品集其他作品的url
  with_file: false #是否合并并发送音频文件
  max_merge_file_num: 10 #最大合并文件数
  gray_layer: true #是否开启灰度图功能
  asmr_level: 0

  send_type: file   #record或者file，record是语音，file是文件
  channels: #频道来源。此功能需要配置proxy，并通过tools完成登录。
    - '@emococh'
    - '@-gabisroom-4153'
jmcomic:
  jm_comic_search_level: 0  #jm搜索功能所需权限等级
  jm_comic_download_level: 0          #jm下载功能所需权限等级
iwara:
  iwara_search_level: 0  #iwara搜索功能所需权限等级
  iwara_download_level: 9  #iwara下载功能所需权限等级
  iwara_gray_layer: true #是否开启iwara灰度图功能
  zip_file: false #是否压缩文件
  zip_password: "123456" #压缩密码
JMComic:                  #禁漫相关功能设置
  anti_nsfw: black_and_white   #防吞策略，可选gif、black_and_white、no_censor
  gif_compress: false     #gif模式下是否压缩
  previewPages: 6         #验车预览页数
  autoClearPDF: True      #下载后自动清除pdf
  savePath: "data/pictures/benzi"  #下载为pdf的默认保存路径

