
user_handle_logic: blacklist #模式。可填 blacklist, whitelist。blacklist下，屏蔽指定用户，whitelist下，只处理指定用户。
user_handle_logic_operate_level: 1000 #拉黑、解黑用户所需操作权限
group_handle_logic: blacklist #模式。可填 blacklist, whitelist。blacklist下，屏蔽指定群，whitelist下，只处理指定群。
group_handle_logic_operate_level: 1000 #拉黑、解黑群所需操作权限
邀请bot加群所需权限: 0
申请bot好友所需权限: 0
webui:
  enable: true #是否开启web ui
record_mface: true #是否收集主人的表情包
proxy:
  http_proxy: ""
  socks_proxy: ""
bot: "Eridanus"   #机器人昵称
master:
  name: "管理员"
  id: 1840094972
group: 879886836   #测试群号1，随便建个小群。bot会往里面发乱七八糟的东西，不要填用户群。
adapter:
  name: "any"   #兼容性选项，如果用Lagrange，则必须填Lagrange，用其他onebot实现则不用动
  ws_client:   #机器人作为websocket客户端
    ws_link: "ws://127.0.0.1:3001"  #bot的websocket请求地址


help_menu:
  content:
    page1:
      - { 'type': 'basic_set', 'img_width': 1000,'img_name_save': 'help_menu_page1.png','img_height': 1500,'max_num_of_columns': 3 ,'font_common_size': 34,'font_des_size': 25, 'font_title_size': 46,'spacing': 3,'padding_up': 30}
      - { 'type': 'avatar', 'img': ["https://q1.qlogo.cn/g?b=qq&nk=2319804644&s=640"],'content': ["[name]枫与岚[/name]\n[des]很高兴认识你～[/des]"],'padding_up_font': 5,'upshift_extra':20 }
      - '你好，这里 [title]枫与岚[/title] 哦\n我是一个基于 [title]Eridanus[/title] 的qq机器人，请多关照!!!'
      - {'type': 'text','content': ['  现在（敲黑板）！枫与岚也有属于自己的人物形象啦，大家请看！'],'layer':2}
      - { 'type': 'img', 'subtype': 'common_with_des','layer':2, 'img': ['https://gal.manshuo.ink/usr/uploads/2025/07/977611811.png','https://gal.manshuo.ink/usr/uploads/2025/07/2873643637.png','https://gal.manshuo.ink/usr/uploads/2025/07/4007464159.png'],'content': ["感谢’邪恶饼干‘的绘制","感谢’欢乐阳光‘的绘制","感谢’枫糖松饼’的绘制‘"] }
      - {'type': 'text','content': ['好耶，这下枫与岚也是变得越来越可爱了呢（嗯！\n那么接下来，就让我们介绍枫与岚的奇妙能力吧！'],'layer':2}
      - '   '
      - { 'type': 'img', 'subtype': 'common_with_des_right','img': [ "https://q1.qlogo.cn/g?b=qq&nk=1270858640&s=640" ],'label': [ 'B站' ],'content': [ ' \n这是我们的\n                 ---漫朔\n \n[des]关注漫朔谢谢喵喵[/des]' ] }
      - {'type': 'text','content': ['[title]枫与岚の功能菜单[/title]\n· AL对话（艾特触发\n· 车队提醒\n(创建车队 +队伍名称、发车 +队伍名称、加入 +队伍名称)\n· 大量定时任务推送\n· Bangumi（番剧）查询\n· Galgame查询/gal推荐\n· 雀魂查询、雀魂记录\n（支持三麻以及四麻查询，仅有金之间以上数据）'],'layer':2}
      - {'type': 'text','content': ['· 多平台链接解析\n（BiliBili、抖音、小红书、微博、推特等）\n· BiliBili动态实时推送\n· PetPet绘图（咕咕咕）\n· 奶龙/doro检测\n· arcaea online\n（暂不维护（强制要求拥有arcaea online）\n· 黑/白名单、权限系统\n(目前有身份：管理员、信任者、贡献者、用户)\n（授权指令：授权 + 身份）\n· 敬请期待（欢迎催更，咕咕咕！'],'layer':2}
      - '   '
      - {'type': 'text','content': ['[title]限制级の功能菜单[/title]\n[des]注意：本功能模块均为限制级，请群友谨慎使用，部分功能未获得对应授权不予开放，请进入bot群（674822468）请求 MASTER 授权[/des]'],'layer':2}
      - {'type': 'text','content': ['随机asmr（R18）\n· JMComic 系列（验车 + id、JM下载 + id、随机本子等）\n· iwara热门（包括搜索特定视频与下载功能）'],'layer':2}
      - '   '
      - {'type': 'text','content': ['[title]小功能の菜单[/title]\n· 今日老婆/群主/群友/塔罗/老公/萝莉等\n· 🦌（这是一种生活、一种签到方式）\n· /透/娶群友系列\n· 点歌功能 （点歌 周杰伦 屋顶）\n· z_lib搜书/下载\n· 搜图 + 图片\n· 内置ai绘图（暂不开放）'],'layer':2}


