bot:
  name: "Eridanus"
master:
  name: "主人"
  id: 1840094972
webui: True  #将Eridanus连接到webui
group:
  test_group: 879886836   #测试群号1，随便建个小群。bot会往里面发乱七八糟的东西，不要填用户群。
adapter:
  access_token: "any_access_token" #onebot实现部分为空/默认，一般不用改
  ws_client:
    ws_link: "ws://127.0.0.1:3001"  #bot的websocket请求地址
user_handle_logic: blacklist #模式。可填 blacklist, whitelist。blacklist下，屏蔽指定用户，whitelist下，只处理指定用户。
user_handle_logic_operate_level: 1000 #拉黑、解黑用户所需操作权限
group_handle_logic: blacklist #模式。可填 blacklist, whitelist。blacklist下，屏蔽指定群，whitelist下，只处理指定群。
group_handle_logic_operate_level: 1000 #拉黑、解黑群所需操作权限
邀请bot加群所需权限: 0
申请bot好友所需权限: 0
record_mface: true #是否收集主人的表情包


